### ISSUE TITLE
User Authentication process

### ISSUE THREAD

**Issue by Ando22** [idurar/idurar-erp-crm#457]
- Registration
- Login
- Logout

**Comment by Emyboy** [comment]
I am interested in working on this as well.

**Comment by sahith29s** [comment]
I want to work on this can you assign me please?

**Comment by Sathyam1020** [comment]
Can you provide more info on this?

**Comment by parteekcoder** [comment]
Hey @Ando22 there is already login and logout APIs present so we need to update them right in this task and add new registration API

**Comment by parteekcoder** [comment]
Also @Ando22 @salahlalami before proceeding further does the number roles here are fixed like `admin,staff` or user can have custom roles as well?

**Comment by parteekcoder** [comment]
@salahlalami @Ando22  can you please provide more context about this

**Comment by Ando22** [comment]
> @Ando22 @salahlalami There are some questions can you please provide context about them so that can start with the implementation:
> 
> * Do we have only 2 roles `admin and staff`
> * Can user creates custom roles of his choice
> * Can admin create user with role admin also
> * the set of permissions allowed in staff role are fixed? Or admin can edit that?

1. Yes there are only 2 roles as an initial
2. In future yes, but right now, everytime admin create a user, the role will assigned defaultly as `staff`. (we will create a new issue for handling RBAC). create roles it should be for admin
3. Yes admin can create admin
4. yes, it should be fixed as an initial feature

**Comment by parteekcoder** [comment]
> 

thanks, @Ando22 for providing this information, so means the number of roles and permissions assigned to roles should be dynamic (which means can be changed by the user)

**Comment by sarath1326** [comment]
i want to contribute this issue. now is this problems is solved ?

**Comment by niket-malviya** [comment]
i also need to contribute to the following issue can you provide more details

**Comment by sarath1326** [comment]
my name is sarath . from kerala
i am a mern stack developer

**Comment by niket-malviya** [comment]
you haven't provided any update about the problem can you please inform is the issue is still on or not

**Comment by dakshmehta007** [comment]
@Ando22  Can you please tell the status of this issue?

**Comment by Tridib2510** [comment]
I am interested in contributing to this issue. Can you please inform weather this issue is open or not.

**Comment by chandanashetty31** [comment]
I'd like  to work on this issue.. Could you please assign me the task
