### ISSUE TITLE
Create New Payment Error - Page not found 404

### ISSUE THREAD

**Issue by Rostyslav99** [idurar/idurar-erp-crm#849]
**Describe the bug**
Not possible to create new payment /payment/create via UI

**To Reproduce**
1. Go to '/payment/ page
2. Click on 'Add new Payment' button

**Screenshots**
<img width="1604" alt="image" src="https://github.com/idurar/idurar-erp-crm/assets/62433516/aefd3265-a3d3-47ec-973b-641945fb0a5b">

**Comment by pj199611** [comment]
can you please assign me this @Rostyslav99

**Comment by Rostyslav99** [comment]
@pj199611 seems like I can't, sorry

**Comment by prabhjotsourcefuse** [comment]
> @pj199611 seems like I can't, sorry

Hey take the pull it is fixed

**Comment by Rostyslav99** [comment]
> > @pj199611 seems like I can't, sorry
> 
> Hey take the pull it is fixed

what branch?

**Comment by prabhjotsourcefuse** [comment]
> > > @pj199611 seems like I can't, sorry
> > 
> > Hey take the pull it is fixed
> 
> what branch?

I was in the master branch and I didn't see the issue

**Comment by Rostyslav99** [comment]
> > > > @pj199611 seems like I can't, sorry
> > > 
> > > 
> > > Hey take the pull it is fixed
> > 
> > 
> > what branch?
> 
> I was in the master branch and I didn't see the issue

So you can add new payment? It's weird it didn't work for me from beginning and still doesn't

@pj199611 do you have the same issue?

**Comment by Gregsai** [comment]
Hello, 

It was not working for me yesterday and it is not working now either.

**Comment by Rostyslav99** [comment]
> > > > > > @pj199611 seems like I can't, sorry
> > > > > 
> > > > > 
> > > > > Hey take the pull it is fixed
> > > > 
> > > > 
> > > > what branch?
> > > 
> > > 
> > > I was in the master branch and I didn't see the issue
> > 
> > 
> > So you can add new payment? It's weird it didn't work for me from beginning and still doesn't
> > @pj199611 do you have the same issue?
> 
> Wanna connect and discuss??

yes, lets do it

**Comment by prabhjotsourcefuse** [comment]
> seems like there's no /payment/create route on FE side

Do u have discord?

**Comment by Rostyslav99** [comment]
@prabhjotsourcefuse rostyslav#9337

**Comment by prabhjot-brightly** [comment]
let's connect

**Comment by prabhjot-brightly** [comment]
this is mine Masterchief#8826

**Comment by inesmrad** [comment]
Hi i started reproducing your bug with chrome version 123.0.6312.59 with windows being my OS .
When checking the payment section, i found out the data table exists but the add new payment button doesn't.
![Screenshot (607)](https://github.com/idurar/idurar-erp-crm/assets/133030569/fcef56be-25d9-4e1e-bfc2-50cf53d9e674)
